eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8763

spring:
  application:
    name: service-wallet
  session:
    store-type: none

  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.206:3306/myseckill?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # --- DruidDataSource setting ----
    filters: stat,wall,log4j
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 60000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logAbandoned: true
    connectionProperties: stat.mergeSql=true;stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 192.168.1.206
    port: 6379
    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: 100
#  activemq:
#    broker-url: tcp://192.168.1.206:61616
#    in-memory: true
#    pool:
#      enabled: false
myconfig:
  zookeeper:
    url: 192.168.1.206:2181
